import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import {createI18n} from "vue-i18n"

const i18n =createI18n({
   messages: {
    en: {
      Clouds: 'Clouds',
      Rain: 'Rain',
      Temprature:'Temperature',
      Clear:'Clear',
      feelslike:'feels like',
      winddirection:'wind direction',
      windspeed: 'wind speed',
      windmaxspeed:'wind max speed',
      Time:'saacad',
      humidity: 'humidity',
      January : 'January',
      February: 'February',
      March: 'March',
      April: 'April',
      May: 'May',
      June: 'June',
      July: 'July',
      August: 'August',
      September: 'September',
      October: 'October',
      November: 'November',
      December: 'December',
      Sunday: 'Sunday',
      Monday: 'Monday',
      Tuesday: 'Tuesday',
      Wednesday: 'Wednesday',
      Thursday: 'Thursday',
      Friday: 'Friday',
      Saturday: 'Saturday',
       },

    tr: {
     Clouds: "Bulutlu",
     Rain: "Yağmurlu",
     Temprature: "Sıcaklık",
     Clear: "açık",
     Time:'Saat',
     feelslike: 'Hissedilen Sıcaklık ',
     winddirection:'Rüzgar Yönü',
      windspeed: 'Rüzgar Hızı',
      windmaxspeed:'Maks. Rüzgar Hızı ',
     humidity: 'Nem',
     January : 'Ocak',
     February: 'Şubat',
     March: 'Mart',
     April: 'Nisan',
     May: 'Mayıs',
     June: 'Haziran',
     July: 'Temmuz',
     August: 'Ağustos',
     September: 'Eylül',
     October: 'Ekim',
     November: 'Kasım',
     December: 'Aralık',
     Sunday: 'pazar',
     Monday: 'pazartesi',
     Tuesday: 'salı',
     Wednesday: 'çarşamba',
     Thursday: 'perşembe',
     Friday: 'cuma',
     Saturday: 'cumartesi',
    },
    som: {
        Clouds: "Caad",
        Rain: "Roob",
        Temprature: "heerkul",
        Clear: "habo furan",
        feelslike:'dareenkeeda',
        Time:'Saat',
        winddirection:'jıhada dabeesha',
        windspeed: 'xawaraha dabeesha',
        windmaxspeed:'Max. xawaraha dabeesha ',
        humidity: 'huur',
        January : 'Todob',
        February: 'Xeys',
        March: 'Diraac',
        April: 'Seermoweydo',
        May: 'Candhoqoys',
        June: ' Guyar',
        July: 'Xagaa-cadde',
        August: 'Xagaa-madoobe',
        September: 'Karan',
        October: 'Dambarsame',
        November: 'Deyr-halalood',
        December: 'Dallaalo',
        Sunday: 'axad',
        Monday: 'isniin',
        Tuesday: 'talaado',
        Wednesday: 'arbaco',
        Thursday: 'qamiis',
        Friday: 'jimco',
        Saturday: 'sabti',
       }
   }
})

createApp(App).use(router).use(i18n).mount('#app')
